/*
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.mdsd.erdiagram.text


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ERDiagramDslRuntimeModule extends AbstractERDiagramDslRuntimeModule {
}
