/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mdsd.erdiagram.text;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ERDiagramDslRuntimeModule extends AbstractERDiagramDslRuntimeModule {
}
