/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mdsd.erdiagram.text.ui;

import com.google.inject.Injector;
import hu.bme.mit.mdsd.erdiagram.text.ui.internal.TextActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ERDiagramDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(TextActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		TextActivator activator = TextActivator.getInstance();
		return activator != null ? activator.getInjector(TextActivator.HU_BME_MIT_MDSD_ERDIAGRAM_TEXT_ERDIAGRAMDSL) : null;
	}

}
