/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.mdsd.erdiagram.text;

import hu.bme.mit.mdsd.erdiagram.text.ERDiagramDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ERDiagramDslStandaloneSetup extends ERDiagramDslStandaloneSetupGenerated {
  public static void doSetup() {
    ERDiagramDslStandaloneSetup _eRDiagramDslStandaloneSetup = new ERDiagramDslStandaloneSetup();
    _eRDiagramDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
