/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.mdsd.erdiagram.text;

import hu.bme.mit.mdsd.erdiagram.text.AbstractERDiagramDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ERDiagramDslRuntimeModule extends AbstractERDiagramDslRuntimeModule {
}
