/*
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.mdsd.erdiagram.text.parser.antlr;

import com.google.inject.Inject;
import hu.bme.mit.mdsd.erdiagram.text.parser.antlr.internal.InternalERDiagramDslParser;
import hu.bme.mit.mdsd.erdiagram.text.services.ERDiagramDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ERDiagramDslParser extends AbstractAntlrParser {

	@Inject
	private ERDiagramDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalERDiagramDslParser createParser(XtextTokenStream stream) {
		return new InternalERDiagramDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ERDiagram";
	}

	public ERDiagramDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ERDiagramDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
