/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.mdsd.erdiagram.text.ui.contentassist;

import hu.bme.mit.mdsd.erdiagram.text.ui.contentassist.AbstractERDiagramDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ERDiagramDslProposalProvider extends AbstractERDiagramDslProposalProvider {
}
