/**
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.mdsd.erdiagram.text.ui;

import hu.bme.mit.mdsd.erdiagram.text.ui.AbstractERDiagramDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ERDiagramDslUiModule extends AbstractERDiagramDslUiModule {
  public ERDiagramDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
