/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mdsd.erdiagram.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ERDiagramDslUiModule extends AbstractERDiagramDslUiModule {

	public ERDiagramDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
