/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mdsd.erdiagram.text.validation;

import java.util.HashSet;
import java.util.Set;

import org.eclipse.xtext.validation.Check;

import hu.bme.mit.mdsd.erdiagram.text.eRDiagramDsl.ERDiagramDslPackage;
import hu.bme.mit.mdsd.erdiagram.text.eRDiagramDsl.Entity;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ERDiagramDslValidator extends AbstractERDiagramDslValidator {

	@Check
	public void checkCyclicInheritance(Entity entity) {
		checkCyclicInheritance2(entity, new HashSet<Entity>());
	}

	private void checkCyclicInheritance2(Entity entity, Set<Entity> entitiesAlreadyChecked) {
		entitiesAlreadyChecked.add(entity);
		for (Entity parent : entity.getIsA()) {
			if (entitiesAlreadyChecked.contains(parent)) {
				error("Cyclic inheritance is not allowed.",	ERDiagramDslPackage.Literals.ENTITY__IS_A);
				return;
			}
			checkCyclicInheritance2(parent, entitiesAlreadyChecked);
		}
	}
	
}
