/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mdsd.erdiagram.text.ide;


/**
 * Use this class to register ide components.
 */
public class ERDiagramDslIdeModule extends AbstractERDiagramDslIdeModule {
}
