/*
 * generated by Xtext 2.20.0
 */
package hu.bme.mit.mdsd.erdiagram.text.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.mit.mdsd.erdiagram.text.ERDiagramDslRuntimeModule;
import hu.bme.mit.mdsd.erdiagram.text.ERDiagramDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ERDiagramDslIdeSetup extends ERDiagramDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ERDiagramDslRuntimeModule(), new ERDiagramDslIdeModule()));
	}
	
}
