<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trace" nsURI="hu.bme.mit.mdsd.trace" nsPrefix="trace">
  <eClassifiers xsi:type="ecore:EClass" name="TraceRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="traces" upperBound="-1"
        eType="#//Trace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="erdiagramRoot" eType="ecore:EClass ../../hu.bme.mit.mdsd.erdiagram/model/erdiagram.ecore#//EntityRelationDiagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rdbRoot" eType="ecore:EClass ../../hu.bme.mit.mdsd.rdb/model/rdb.ecore#//RelationalDataBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="erdiagramElement" eType="ecore:EClass ../../hu.bme.mit.mdsd.erdiagram/model/erdiagram.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rdbElement" eType="ecore:EClass ../../hu.bme.mit.mdsd.rdb/model/rdb.ecore#//NamedElement"/>
  </eClassifiers>
</ecore:EPackage>
